spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
      cache: false

  datasource:
    url: jdbc:h2:~/quiz
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
